"""Add status to lecturer_availability

Revision ID: 1970c56383ba
Revises: f5a89c1b7a2d
Create Date: 2026-07-11 12:17:02.089831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1970c56383ba'
down_revision: Union[str, Sequence[str], None] = 'f5a89c1b7a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer_availability', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('lecturer_availability', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lecturer_availability', 'reason',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('lecturer_availability', 'status')
    # ### end Alembic commands ###
