"""Add explicit audit log columns

Revision ID: 5a67728a8be3
Revises: b604dc6090b5
Create Date: 2026-07-13 01:48:08.954071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a67728a8be3'
down_revision: Union[str, Sequence[str], None] = 'b604dc6090b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('user_role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'user_role')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'ip_address')
    # ### end Alembic commands ###
