"""initial

Revision ID: 7a51c3393add
Revises: 
Create Date: 2026-04-05 14:42:41.575630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a51c3393add'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_timetable_sessions_session_id'), table_name='timetable_sessions')
    op.drop_table('timetable_sessions')
    op.drop_index(op.f('ix_system_constraints_constraint_id'), table_name='system_constraints')
    op.drop_table('system_constraints')
    op.drop_index(op.f('ix_vehicle_requests_req_id'), table_name='vehicle_requests')
    op.drop_table('vehicle_requests')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_index(op.f('reg_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.alter_column('batches', 'degree_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('batches', 'student_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('batches', 'current_semester',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'batches', 'degrees', ['degree_id'], ['degree_id'])
    op.add_column('degrees', sa.Column('code', sa.String(length=50), nullable=False))
    op.alter_column('degrees', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('degrees', 'duration_years',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'degrees', ['code'])
    op.drop_column('degrees', 'dept_id')
    op.alter_column('departments', 'faculty_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('departments', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'departments', 'faculties', ['faculty_id'], ['faculty_id'])
    op.alter_column('faculties', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_unique_constraint(None, 'faculties', ['name'])
    op.add_column('lecturer_availability', sa.Column('start_time', sa.String(length=10), nullable=False))
    op.add_column('lecturer_availability', sa.Column('end_time', sa.String(length=10), nullable=False))
    op.alter_column('lecturer_availability', 'lecturer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'lecturer_availability', 'users', ['lecturer_id'], ['user_id'])
    op.drop_column('lecturer_availability', 'reason')
    op.drop_column('lecturer_availability', 'unavailable_start')
    op.drop_column('lecturer_availability', 'unavailable_end')
    op.alter_column('lecturers', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('lecturers', 'dept_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'lecturers', ['staff_id'])
    op.create_foreign_key(None, 'lecturers', 'users', ['user_id'], ['user_id'])
    op.alter_column('modules', 'dept_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('modules', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('modules', 'code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('modules', 'credits',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'modules', 'departments', ['dept_id'], ['dept_id'])
    op.drop_column('modules', 'degree_id')
    op.drop_column('modules', 'is_active')
    op.drop_column('modules', 'lecture_hours_per_week')
    op.alter_column('resource_managers', 'assigned_section',
               existing_type=mysql.ENUM('TRANSPORT', 'EVENTS', 'GENERAL', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               nullable=False)
    op.create_foreign_key(None, 'resource_managers', 'users', ['user_id'], ['user_id'])
    op.alter_column('resources', 'type',
               existing_type=mysql.ENUM('LECTURE_HALL', 'LAB', 'AUDITORIUM', 'GROUND', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('resources', 'facilities',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_unique_constraint(None, 'resources', ['name'])
    op.alter_column('students', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('students', 'batch_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['user_id'])
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('SUPER_ADMIN', 'SCHEDULER', 'LECTURER', 'STUDENT', 'RESOURCE_MANAGER', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'contact_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'contact_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('SUPER_ADMIN', 'SCHEDULER', 'LECTURER', 'STUDENT', 'RESOURCE_MANAGER', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.alter_column('students', 'batch_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('students', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'resources', type_='unique')
    op.alter_column('resources', 'facilities',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.alter_column('resources', 'type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('LECTURE_HALL', 'LAB', 'AUDITORIUM', 'GROUND', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
    op.drop_constraint(None, 'resource_managers', type_='foreignkey')
    op.alter_column('resource_managers', 'assigned_section',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('TRANSPORT', 'EVENTS', 'GENERAL', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.add_column('modules', sa.Column('lecture_hours_per_week', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('modules', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('modules', sa.Column('degree_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='foreignkey')
    op.alter_column('modules', 'credits',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('modules', 'code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
    op.alter_column('modules', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('modules', 'dept_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'lecturers', type_='foreignkey')
    op.drop_constraint(None, 'lecturers', type_='unique')
    op.alter_column('lecturers', 'dept_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('lecturers', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('lecturer_availability', sa.Column('unavailable_end', mysql.TIME(), nullable=False))
    op.add_column('lecturer_availability', sa.Column('unavailable_start', mysql.TIME(), nullable=False))
    op.add_column('lecturer_availability', sa.Column('reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.drop_constraint(None, 'lecturer_availability', type_='foreignkey')
    op.alter_column('lecturer_availability', 'lecturer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('lecturer_availability', 'end_time')
    op.drop_column('lecturer_availability', 'start_time')
    op.drop_constraint(None, 'faculties', type_='unique')
    op.alter_column('faculties', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.alter_column('departments', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.alter_column('departments', 'faculty_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('degrees', sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'degrees', type_='unique')
    op.alter_column('degrees', 'duration_years',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('degrees', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    op.drop_column('degrees', 'code')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.alter_column('batches', 'current_semester',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('batches', 'student_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('batches', 'degree_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reg_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('driver_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('reg_number'), 'vehicles', ['reg_number'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('details', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('log_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_table('vehicle_requests',
    sa.Column('req_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('requested_by_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vehicle_type_needed', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('passenger_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('trip_date', mysql.DATETIME(), nullable=False),
    sa.Column('destination', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=True),
    sa.Column('assigned_vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('req_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_vehicle_requests_req_id'), 'vehicle_requests', ['req_id'], unique=False)
    op.create_table('system_constraints',
    sa.Column('constraint_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('value', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', mysql.ENUM('HARD', 'SOFT'), nullable=False),
    sa.PrimaryKeyConstraint('constraint_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_system_constraints_constraint_id'), 'system_constraints', ['constraint_id'], unique=False)
    op.create_table('timetable_sessions',
    sa.Column('session_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lecturer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('batch_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('type', mysql.ENUM('LECTURE', 'PRACTICAL'), nullable=False),
    sa.Column('status', mysql.ENUM('DRAFT', 'PUBLISHED'), nullable=True),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_timetable_sessions_session_id'), 'timetable_sessions', ['session_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organizer_user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=True),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    # ### end Alembic commands ###
