"""Add multiple vehicle assignments

Revision ID: b604dc6090b5
Revises: cf6d1209b344
Create Date: 2026-07-12 01:37:35.617046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b604dc6090b5'
down_revision: Union[str, Sequence[str], None] = 'cf6d1209b344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('vehicle_requests_ibfk_2'), 'vehicle_requests', type_='foreignkey')
    op.drop_column('vehicle_requests', 'assigned_vehicle_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_requests', sa.Column('assigned_vehicle_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vehicle_requests_ibfk_2'), 'vehicle_requests', 'vehicles', ['assigned_vehicle_id'], ['vehicle_id'], ondelete='SET NULL')
    # ### end Alembic commands ###
