"""add event_type to event_requests

Revision ID: be6ba6421d3c
Revises: e1f3b2a9c8d7
Create Date: 2026-06-10 17:26:44.708946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6ba6421d3c'
down_revision: Union[str, Sequence[str], None] = 'e1f3b2a9c8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_requests', sa.Column('event_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_requests', 'event_type')
    # ### end Alembic commands ###
