"""Initial migration - all tables

Revision ID: bfe8a6871723
Revises: 
Create Date: 2026-02-07 01:33:26.066136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe8a6871723'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('faculty_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dean_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_index(op.f('ix_faculties_faculty_id'), 'faculties', ['faculty_id'], unique=False)
    op.create_table('resources',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('LECTURE_HALL', 'LAB', 'AUDITORIUM', 'GROUND', name='resourcetype'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('facilities', sa.Text(), nullable=True),
    sa.Column('building', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resources_resource_id'), 'resources', ['resource_id'], unique=False)
    op.create_table('system_constraints',
    sa.Column('constraint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('HARD', 'SOFT', name='constrainttype'), nullable=False),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_index(op.f('ix_system_constraints_constraint_id'), 'system_constraints', ['constraint_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'SCHEDULER', 'LECTURER', 'STUDENT', 'RESOURCE_MANAGER', name='userrole'), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reg_number', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('reg_number')
    )
    op.create_index(op.f('ix_vehicles_vehicle_id'), 'vehicles', ['vehicle_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.faculty_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_index(op.f('ix_departments_dept_id'), 'departments', ['dept_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('organizer_user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=150), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=True),
    sa.ForeignKeyConstraint(['organizer_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_table('resource_managers',
    sa.Column('manager_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_section', sa.Enum('TRANSPORT', 'EVENTS', 'GENERAL', name='resourcesection'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manager_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_resource_managers_manager_id'), 'resource_managers', ['manager_id'], unique=False)
    op.create_table('vehicle_requests',
    sa.Column('req_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_needed', sa.String(length=50), nullable=True),
    sa.Column('passenger_count', sa.Integer(), nullable=True),
    sa.Column('trip_date', sa.DateTime(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='requeststatus'), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.vehicle_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('req_id')
    )
    op.create_index(op.f('ix_vehicle_requests_req_id'), 'vehicle_requests', ['req_id'], unique=False)
    op.create_table('degrees',
    sa.Column('degree_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('degree_id')
    )
    op.create_index(op.f('ix_degrees_degree_id'), 'degrees', ['degree_id'], unique=False)
    op.create_table('lecturers',
    sa.Column('lecturer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lecturer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_lecturers_lecturer_id'), 'lecturers', ['lecturer_id'], unique=False)
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('student_count', sa.Integer(), nullable=False),
    sa.Column('current_semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.degree_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batches_batch_id'), 'batches', ['batch_id'], unique=False)
    op.create_table('lecturer_availability',
    sa.Column('avail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('unavailable_start', sa.Time(), nullable=False),
    sa.Column('unavailable_end', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avail_id')
    )
    op.create_index(op.f('ix_lecturer_availability_avail_id'), 'lecturer_availability', ['avail_id'], unique=False)
    op.create_table('modules',
    sa.Column('module_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('lecture_hours_per_week', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.degree_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_modules_module_id'), 'modules', ['module_id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('reg_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_table('timetable_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('type', sa.Enum('LECTURE', 'PRACTICAL', name='sessiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='sessionstatus'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturers.lecturer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_timetable_sessions_session_id'), 'timetable_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_sessions_session_id'), table_name='timetable_sessions')
    op.drop_table('timetable_sessions')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_modules_module_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_lecturer_availability_avail_id'), table_name='lecturer_availability')
    op.drop_table('lecturer_availability')
    op.drop_index(op.f('ix_batches_batch_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_lecturers_lecturer_id'), table_name='lecturers')
    op.drop_table('lecturers')
    op.drop_index(op.f('ix_degrees_degree_id'), table_name='degrees')
    op.drop_table('degrees')
    op.drop_index(op.f('ix_vehicle_requests_req_id'), table_name='vehicle_requests')
    op.drop_table('vehicle_requests')
    op.drop_index(op.f('ix_resource_managers_manager_id'), table_name='resource_managers')
    op.drop_table('resource_managers')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_departments_dept_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicles_vehicle_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_constraints_constraint_id'), table_name='system_constraints')
    op.drop_table('system_constraints')
    op.drop_index(op.f('ix_resources_resource_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_faculties_faculty_id'), table_name='faculties')
    op.drop_table('faculties')
    # ### end Alembic commands ###
