"""Add document_path to booking models

Revision ID: cf6d1209b344
Revises: 1970c56383ba
Create Date: 2026-07-11 16:40:56.823504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6d1209b344'
down_revision: Union[str, Sequence[str], None] = '1970c56383ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_requests', sa.Column('document_path', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('document_path', sa.String(length=255), nullable=True))
    op.add_column('vehicle_requests', sa.Column('document_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_requests', 'document_path')
    op.drop_column('events', 'document_path')
    op.drop_column('event_requests', 'document_path')
    # ### end Alembic commands ###
